### ISSUE TITLE
I want to add Navbar to the site 

### ISSUE THREAD

**Issue by real-coder007Ravi** [baekusboo/music-website#120]
Enhancement of the site to make it look good and modern as New Age websites

**Comment by baekusboo** [comment]
Could you give me a brief on why navbar should be added? I feel there is no usecase of adding a navbar in this project.

**Comment by real-coder007Ravi** [comment]
@baekusboo We can make navbar so that we can add different pages for the site like home page will contain introduction of the site then music page showing all the relevant songs give the user functionaliry to add new song and similiarly some contact information of connecting with us like github profile and linkedin profile. I am planning to do like this

**Comment by baekusboo** [comment]
Since, this project is made to be a webpage and not a website.. I don't really feel the need to have a navbar. The social links for contact are already present in the footer. Also, wait for the issue to be assigned before raising the PR.

You are always welcomed to create an issue for adding any new feature in the webpage or report and fix a bug! Happy Hacking! ^^
